create extension if not exists btree_gist;
create type public.app_role as enum ('Student','Faculty','Lab Staff','Coordinator','Admin');
create type public.booking_status as enum ('Draft','Pending Approval','Approved','Reserved','In Use','Completed','Rejected','Cancelled','Returned Late','Damaged');
create table public.departments (id uuid primary key default gen_random_uuid(), name text not null unique, archived boolean not null default false);
create table public.profiles (id uuid primary key references auth.users(id) on delete restrict, name text not null, email text not null, role public.app_role not null default 'Student', department_id uuid references public.departments(id), late_count integer not null default 0 check(late_count>=0), restricted_until timestamptz, active boolean not null default true, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, archived boolean not null default false);
create table public.labs (id uuid primary key default gen_random_uuid(), name text not null, department_id uuid not null references public.departments(id), capacity integer not null check(capacity>0), location text not null, facilities text[] not null default '{}', status text not null default 'Available' check(status in ('Available','Maintenance','Closed')), description text not null default '', image_url text, archived boolean not null default false, created_at timestamptz not null default now());
create table public.equipment (id uuid primary key default gen_random_uuid(), name text not null, category text not null, category_id uuid references public.categories(id), total_quantity integer not null check(total_quantity>=0), lab_id uuid not null references public.labs(id), condition text not null default 'Good', maintenance_status boolean not null default false, unit_value_high boolean not null default false, description text not null default '', image_url text, archived boolean not null default false, created_at timestamptz not null default now());
create table public.bookings (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), lab_id uuid references public.labs(id), start_at timestamptz not null, end_at timestamptz not null, purpose text not null check(length(trim(purpose))>=3), attendees integer not null default 1 check(attendees>0), notes text not null default '', booking_status public.booking_status not null default 'Pending Approval', approval_status text not null default 'Pending' check(approval_status in ('Pending','Approved','Rejected')), approved_by uuid references public.profiles(id), priority integer not null default 0, decision_reason text, late_recorded boolean not null default false, created_at timestamptz not null default now(), check(start_at<end_at), constraint lab_no_overlap exclude using gist (lab_id with =, tstzrange(start_at,end_at,'[)') with &&) where (booking_status in ('Pending Approval','Approved','Reserved','In Use')));
create table public.booking_items (booking_id uuid not null references public.bookings(id), equipment_id uuid not null references public.equipment(id), quantity integer not null check(quantity>0), primary key(booking_id,equipment_id));
create table public.issue_returns (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id), equipment_id uuid not null references public.equipment(id), quantity integer not null check(quantity>0), issued_at timestamptz not null default now(), due_at timestamptz not null, returned_quantity integer not null default 0 check(returned_quantity>=0 and returned_quantity<=quantity), returned_at timestamptz, issue_condition text not null default 'Good', return_condition text, remarks text, damage_note text, issued_by uuid not null references public.profiles(id), returned_by uuid references public.profiles(id), unique(booking_id,equipment_id));
create table public.resource_blocks (id uuid primary key default gen_random_uuid(), lab_id uuid references public.labs(id), equipment_id uuid references public.equipment(id), start_at timestamptz not null, end_at timestamptz not null, reason text not null, actor uuid not null references public.profiles(id), created_at timestamptz not null default now(), check(start_at<end_at), check(num_nonnulls(lab_id,equipment_id)=1));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), booking_id uuid references public.bookings(id), message text not null, category text not null default 'Bookings', read boolean not null default false, created_at timestamptz not null default now());
create table public.audit_log (id uuid primary key default gen_random_uuid(), actor uuid references public.profiles(id), action text not null, entity text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create table public.rules (key text primary key, value jsonb not null, description text not null default '', updated_at timestamptz not null default now());
create table public.department_rules(department_id uuid not null references public.departments(id),key text not null references public.rules(key),value jsonb not null,primary key(department_id,key));
alter table public.department_rules enable row level security;
revoke all on public.department_rules from anon,authenticated;
grant all on public.department_rules to service_role;

create index bookings_user_start on public.bookings(user_id,start_at desc);
create index booking_items_equipment on public.booking_items(equipment_id,booking_id);
create index issue_returns_unreturned on public.issue_returns(equipment_id,due_at) where returned_at is null;
create index notifications_user_created on public.notifications(user_id,created_at desc);
create index labs_department on public.labs(department_id);
create index equipment_lab on public.equipment(lab_id);
create index profiles_department on public.profiles(department_id);
create index blocks_lab on public.resource_blocks(lab_id,start_at,end_at);
create index blocks_equipment on public.resource_blocks(equipment_id,start_at,end_at);
create index audit_created on public.audit_log(created_at desc);
-- No browser data policies: all application reads/mutations pass through the verified server DAL.
do $$ declare t text; begin foreach t in array array['departments','profiles','categories','labs','equipment','bookings','booking_items','issue_returns','resource_blocks','notifications','audit_log','rules'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant all on public.%I to service_role',t); end loop; end $$;
create function public.rule_number(p_key text,p_default numeric) returns numeric language sql stable set search_path=public as $$ select coalesce((select (value #>> '{}')::numeric from rules where key=p_key),p_default) $$;
create function public.rule_for_actor(p_actor uuid,p_key text,p_default numeric) returns numeric language sql stable set search_path=public as $$ select coalesce((select (d.value #>> '{}')::numeric from department_rules d join profiles p on p.department_id=d.department_id where p.id=p_actor and d.key=p_key),rule_number(p_key,p_default)) $$;
create function public.require_actor(p_actor uuid) returns public.profiles language plpgsql stable set search_path=public as $$ declare a profiles; begin select * into a from profiles where id=p_actor and active; if not found then raise exception 'Permission denied: active profile required' using errcode='42501'; end if; return a; end $$;
create function public.authorize_department(p_actor uuid,p_department uuid,p_roles public.app_role[]) returns void language plpgsql stable set search_path=public as $$ declare a profiles; begin a:=require_actor(p_actor); if not a.role=any(p_roles) or (a.role<>'Admin' and a.department_id is distinct from p_department) then raise exception 'Permission denied for this department' using errcode='42501'; end if; end $$;
-- Sweep interval boundaries; consecutive reservations are never incorrectly summed.
create function public.equipment_available(p_equipment_id uuid,p_start_at timestamptz,p_end_at timestamptz,p_exclude_booking uuid default null) returns integer language sql stable set search_path=public as $$
with e as (select * from equipment where id=p_equipment_id), intervals as (
 select greatest(b.start_at,p_start_at) s, least(b.end_at,p_end_at) f, i.quantity q from booking_items i join bookings b on b.id=i.booking_id where i.equipment_id=p_equipment_id and b.id is distinct from p_exclude_booking and b.booking_status in ('Pending Approval','Approved','Reserved','In Use') and b.start_at<p_end_at and b.end_at>p_start_at
 union all
 select p_start_at,p_end_at,ir.quantity-ir.returned_quantity from issue_returns ir join bookings b on b.id=ir.booking_id where ir.equipment_id=p_equipment_id and ir.returned_at is null and ir.booking_id is distinct from p_exclude_booking and ir.due_at<=now() and p_start_at<=now()+interval '15 minutes' and not(b.start_at<p_end_at and b.end_at>p_start_at)
), events as (select s t,q delta from intervals union all select f,-q from intervals), grouped as (select t,sum(delta) delta from events group by t), occupancy as (select sum(delta) over(order by t) used from grouped)
select case when e.archived or e.maintenance_status or e.condition='Damaged' or exists(select 1 from resource_blocks r where r.equipment_id=e.id and r.start_at<p_end_at and r.end_at>p_start_at) or exists(select 1 from labs l where l.id=e.lab_id and (l.archived or l.status<>'Available')) or exists(select 1 from resource_blocks r where r.lab_id=e.lab_id and r.start_at<p_end_at and r.end_at>p_start_at) then 0 else greatest(0,e.total_quantity-coalesce((select max(used)::integer from occupancy),0)) end from e;
$$;
create function public.validate_request(p_actor uuid,p_lab_id uuid,p_start_at timestamptz,p_end_at timestamptz,p_attendees integer,p_items jsonb) returns void language plpgsql stable set search_path=public as $$
declare a profiles; l labs; item record; e equipment; begin
 a:=require_actor(p_actor);
 if p_start_at is null or p_end_at is null or p_start_at>=p_end_at or p_start_at<now()-interval '1 minute' then raise exception 'Choose a future date and valid time range'; end if;
 if p_end_at-p_start_at>make_interval(hours=>rule_for_actor(p_actor,'max_duration_hours',4)::integer) or p_start_at>now()+make_interval(days=>rule_for_actor(p_actor,'max_advance_days',14)::integer) then raise exception 'Request exceeds duration or advance booking limit'; end if;
 if a.restricted_until>now() or a.late_count>=rule_for_actor(p_actor,'late_return_limit',3) then raise exception 'Booking restricted due to late returns; contact your coordinator'; end if;
 if p_lab_id is null and jsonb_array_length(coalesce(p_items,'[]'))=0 then raise exception 'Select a lab or equipment'; end if;
 if p_attendees is null or p_attendees<1 then raise exception 'Attendees must be positive'; end if;
 if p_lab_id is not null then select * into l from labs where id=p_lab_id; if not found or l.archived or l.status<>'Available' then raise exception 'Lab unavailable or in maintenance'; end if; if p_attendees>l.capacity then raise exception 'Attendees exceed lab capacity'; end if; if exists(select 1 from resource_blocks where lab_id=p_lab_id and start_at<p_end_at and end_at>p_start_at) then raise exception 'Lab blocked for selected time'; end if; if exists(select 1 from bookings where lab_id=p_lab_id and booking_status='In Use' and end_at<now() and p_start_at<=now()+interval '15 minutes') then raise exception 'Lab currently occupied by an overdue booking'; end if; end if;
 for item in select (x->>'equipment_id')::uuid id,sum((x->>'quantity')::integer)::integer quantity from jsonb_array_elements(coalesce(p_items,'[]')) x group by 1 loop
 if item.quantity<1 or item.quantity>rule_for_actor(p_actor,'max_quantity_per_user',10) then raise exception 'Equipment quantity exceeds per-user limit'; end if;
 select * into e from equipment where id=item.id; if not found then raise exception 'Equipment does not exist'; end if;
 if equipment_available(item.id,p_start_at,p_end_at)<item.quantity then raise exception 'Equipment conflict: insufficient quantity for this time'; end if;
 if item.quantity+coalesce((select max(used) from (select sum(delta) over(order by t) used from (select t,sum(delta) delta from (select greatest(b.start_at,p_start_at) t,i.quantity delta from booking_items i join bookings b on b.id=i.booking_id where b.user_id=p_actor and i.equipment_id=item.id and b.booking_status in ('Pending Approval','Approved','Reserved','In Use') and b.start_at<p_end_at and b.end_at>p_start_at union all select least(b.end_at,p_end_at),-i.quantity from booking_items i join bookings b on b.id=i.booking_id where b.user_id=p_actor and i.equipment_id=item.id and b.booking_status in ('Pending Approval','Approved','Reserved','In Use') and b.start_at<p_end_at and b.end_at>p_start_at) events group by t) grouped) occupancy),0)>rule_for_actor(p_actor,'max_quantity_per_user',10) then raise exception 'Combined requests exceed your equipment quantity limit'; end if;
 end loop;
end $$;
create function public.create_booking(p_actor uuid,p_lab_id uuid,p_start_at timestamptz,p_end_at timestamptz,p_purpose text,p_attendees integer,p_items jsonb,p_notes text) returns uuid language plpgsql set search_path=public as $$
declare bid uuid; a profiles; begin
 perform 1 from labs where id=p_lab_id or id in(select e.lab_id from equipment e where e.id in(select (x->>'equipment_id')::uuid from jsonb_array_elements(coalesce(p_items,'[]')) x)) order by id for update;
 perform 1 from equipment where id in(select (x->>'equipment_id')::uuid from jsonb_array_elements(coalesce(p_items,'[]')) x) order by id for update;
 perform validate_request(p_actor,p_lab_id,p_start_at,p_end_at,p_attendees,p_items); a:=require_actor(p_actor);
 insert into bookings(user_id,lab_id,start_at,end_at,purpose,attendees,notes,priority) values(p_actor,p_lab_id,p_start_at,p_end_at,trim(p_purpose),p_attendees,coalesce(p_notes,''),case when a.role='Faculty' then 1 else 0 end) returning id into bid;
 insert into booking_items select bid,(x->>'equipment_id')::uuid,sum((x->>'quantity')::integer)::integer from jsonb_array_elements(coalesce(p_items,'[]')) x group by 2;
 insert into audit_log(actor,action,entity,entity_id,after_data) values(p_actor,'booking.created','bookings',bid,(select to_jsonb(b) from bookings b where id=bid));
 insert into notifications(user_id,booking_id,message) values(p_actor,bid,'Your booking request has been submitted for approval.');
 return bid;
end $$;

