import { availableQuantity } from '@/lib/availability';
import Link from 'next/link';
import { CalendarDays, Clock3, Users, MapPin, ChevronRight, FlaskConical, Package, Search, Inbox, CheckCircle2 } from 'lucide-react';
import ResourceImage from '@/components/screens/resource-image';

export type Row = Record<string, any>;
export type Data = { profile: Row; labs: Row[]; equipment: Row[]; bookings: Row[]; availability: Row[]; booking_items: Row[]; profiles: Row[]; departments: Row[]; notifications: Row[]; rules: Row[]; resource_blocks: Row[]; issue_returns: Row[]; audit_log: Row[]; blocks?: Row[]; issues?: Row[]; inventoryCustody?: Row[]; categories?: Row[] };
export const date = (value: string) => new Date(value).toLocaleDateString('en-GB', {timeZone:'Asia/Karachi', weekday:'short', day:'numeric',month:'short',year:'numeric'});
export const time = (value: string) => new Date(value).toLocaleTimeString('en-GB',{timeZone:'Asia/Karachi',hour:'numeric',minute:'2-digit',hour12:true});
export const isActive = (b: Row) => ['Pending Approval','Approved','Reserved','In Use'].includes(b.booking_status);
export const department = (data:Data,id:string) => data.departments.find(x=>x.id===id)?.name || 'University';
export const labName = (data:Data,id:string) => data.labs.find(x=>x.id===id)?.name || 'Equipment request';
export const ownerName = (data:Data,id:string) => data.profiles.find(x=>x.id===id)?.name || 'University member';
export function Badge({status}:{status:string}) {const tone = /reject|cancel|damage|closed|busy|maintenance/i.test(status)?'danger':/pending|limited|late|overdue/i.test(status)?'warning':/available|approved|reserved|complete|good|returned/i.test(status)?'success':'blue'; return <span className={`badge badge-${tone}`}><span className="status-dot"/>{status}</span>;}
export function Heading({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="page-heading"><div><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</div>;}
export function Empty({title='Nothing here yet',description='New activity will appear here.',href,label}:{title?:string;description?:string;href?:string;label?:string}){return <div className="empty-state card"><span className="empty-icon"><Inbox size={32}/></span><h3>{title}</h3><p className="muted">{description}</p>{href&&<Link className="btn btn-primary" href={href}>{label||'Explore resources'} <ChevronRight size={16}/></Link>}</div>;}
export function Section({title,href,children}:{title:string;href?:string;children:React.ReactNode}){return <section className="screen-section"><div className="section-heading"><h2>{title}</h2>{href&&<Link href={href}>View all <ChevronRight size={16}/></Link>}</div>{children}</section>;}
export function SearchForm({placeholder='Search labs, equipment or departments…',query='',children,action}:{placeholder?:string;query?:string;children?:React.ReactNode;action?:string}){return <form className="filter-form" action={action}><div className="search-bar"><Search size={20}/><input aria-label={placeholder} name="q" defaultValue={query} placeholder={placeholder}/><button className="btn btn-primary" aria-label="Search"><Search size={20}/></button></div>{children&&<div className="filter-bar">{children}<button className="btn btn-secondary">Apply filters</button></div>}</form>;}
export function LabCard({lab,data,compact=false}:{lab:Row;data:Data;compact?:boolean}){const highDemand = data.bookings?.filter((b:Row) => b.lab_id === lab.id && isActive(b) && new Date(b.start_at) > new Date()).length > 3; return <Link href={`/labs/${lab.id}`} className={`resource-card card lab-card ${compact?'lab-card-compact':''}`}><ResourceImage resource={lab}/><div className="resource-card-body"><div className="resource-title"><h3>{lab.name}</h3><Badge status={lab.status||lab.operational_status||'Available'}/></div><p className="muted">{department(data,lab.department_id)}</p><div className="metadata"><span><Users size={16}/>{lab.capacity} seats</span><span><MapPin size={16}/>{lab.location}</span></div><div className="facility-chips">{(Array.isArray(lab.facilities)?lab.facilities:[]).slice(0,3).map((f:string)=><span key={f}>{f}</span>)}</div>{highDemand&&<div style={{marginTop:'0.5rem'}}><Badge status="High Demand Forecast" /></div>}<span className="resource-link">View lab <ChevronRight size={18}/></span></div></Link>;}
export function EquipmentCard({item,data,start,end}:{item:Row;data:Data;start?:string;end?:string}){const quantity=start&&end?availableQuantity(item as any,start,end,{...data,blocks:data.blocks||data.resource_blocks,issues:data.issues||data.issue_returns} as any):null; const recommendMaintenance = data.issue_returns?.filter((i:Row) => i.equipment_id === item.id && i.return_condition === 'Damaged').length > 1; return <Link href={`/equipment/${item.id}`} className="resource-card card equipment-card"><ResourceImage resource={item} equipment/><div className="resource-card-body"><h3>{item.name}</h3><div className="metadata"><span><Package size={15}/>{quantity===null?item.total_quantity:quantity} {quantity===null?"total units":"available units"}</span><span><MapPin size={15}/>{labName(data,item.lab_id)}</span></div><p className="muted">{item.category}</p><Badge status={item.maintenance_status===true?'Maintenance':item.total_quantity>0?'Available':'Unavailable'}/>{recommendMaintenance&&<div style={{marginTop:'0.5rem'}}><Badge status="Maintenance Recommended"/></div>}{item.unit_value_high&&<span className="high-value">High-value • coordinator approval</span>}</div></Link>;}
export function BookingCard({booking:b,data}:{booking:Row;data:Data}) {const lab=data.labs.find(x=>x.id===b.lab_id);return <Link href={`/bookings/${b.id}`} className="booking-card card">{lab?<ResourceImage resource={lab}/>:<div className="booking-icon"><Package size={25}/></div>}<div className="booking-card-body"><div className="resource-title"><h3>{labName(data,b.lab_id)}</h3><Badge status={b.booking_status}/></div><div className="metadata"><span><CalendarDays size={15}/>{date(b.start_at)}</span><span><Clock3 size={15}/>{time(b.start_at)} – {time(b.end_at)}</span></div><p className="muted">{b.purpose}</p></div><ChevronRight className="booking-chevron" size={20}/></Link>;}
export function Stat({value,label,tone='blue',icon}:{value:number|string;label:string;tone?:string;icon:React.ReactNode}) {return <div className={`stat-card stat-${tone}`}><span className="stat-icon">{icon}</span><div><strong>{value}</strong><span>{label}</span></div></div>;}
export function PermissionDenied(){return <Empty title="Permission required" description="Your role does not have access to this workspace." href="/dashboard" label="Back to dashboard"/>;}




