import { getAppData } from '@/lib/dal';
import { calculateAnalytics } from '@/lib/analytics';
import { Admin, Approvals, Blocks, IssueReturn, Rules } from './operations';
import { Dashboard, Browse, ResourceDetail, Bookings, BookingDetail, Calendar, Notifications, Profile, Book } from './student';
import { Data, PermissionDenied, Empty } from './common';
import dynamic from 'next/dynamic';
const Reports=dynamic(()=>import('./reports'));
type Query = Record<string,string|undefined>;
export default async function Screen({screen,id,query={}}:{screen:string;id?:string;query?:Query}){const raw=await getAppData();if(!raw.profile)return <Empty title="Complete your setup" description={raw.configurationError||'Sign in with a university account to access UniLab.'} href="/login" label="Go to sign in"/>;const data:Data={...raw,profile:raw.profile,profiles:Array.from(new Map([...raw.users,...raw.bookings.map(b=>b.profiles).filter(Boolean),raw.profile].map(p=>[p!.id,p!])).values()),resource_blocks:raw.blocks.map(b=>({...b,resource_id:b.lab_id||b.equipment_id})),issue_returns:raw.issues,audit_log:raw.audit,booking_items:raw.bookings.flatMap(b=>b.booking_items.map(i=>({...i,booking_id:b.id})))};return <>{raw.configurationError&&<div role="alert" className="notice notice-danger">{raw.configurationError}</div>}{screen==='dashboard'?<Dashboard data={data}/>:screen==='browse'||screen==='labs'?<Browse data={data} query={query} workspace={screen==='browse'}/>:screen==='lab-detail'?<ResourceDetail data={data} id={id!} tab={query.tab}/>:screen==='equipment'?<Browse equipment data={data} query={query}/>:screen==='equipment-detail'?<ResourceDetail equipment data={data} id={id!} tab={query.tab}/>:screen==='book'?<Book data={data} query={query}/>:screen==='bookings'?<Bookings data={data} tab={query.tab} query={query.q}/>:screen==='booking-detail'?<BookingDetail data={data} id={id!} message={query.message}/>:screen==='calendar'?<Calendar data={data} query={query}/>:screen==='notifications'?<Notifications data={data} tab={query.tab}/>:screen==='profile'?<Profile data={data}/>:screen==='approvals'?<Approvals data={data} tab={query.tab} q={query.q} id={id}/>:screen==='issue-return'?<IssueReturn data={data} tab={query.tab}/>:screen==='blocks'?<Blocks data={data}/>:screen==='rules'?<Rules data={data}/>:screen==='admin'?<Admin data={data} section={id} q={query.q} edit={query.edit}/>:screen==='reports'?['Coordinator','Admin'].includes(data.profile.role)?<Reports analytics={calculateAnalytics(raw)} departmentScoped={data.profile.role==='Coordinator'}/>:<PermissionDenied/>:<Empty title="Page not found" href="/dashboard" label="Go home"/>}</>;}


