import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});
const results=[];
const viewports=[{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}];
for(const viewport of viewports){const page=await browser.newPage({viewport});const checks=[];
try{await page.goto('http://127.0.0.1:4178/?screen=book&role=Student');await page.getByRole('textbox',{name:'Purpose of booking'}).fill('Embedded systems prototype workshop');await page.getByRole('button',{name:'Add one Arduino Kit'}).click();await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('heading',{name:'Select Date & Time'}).waitFor();const nextDay=new Date(Date.now()+86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'});await page.getByLabel('Date',{exact:true}).fill(nextDay);await page.getByLabel('Start time',{exact:true}).fill('10:00');await page.getByLabel('End time',{exact:true}).fill('12:00');await page.getByRole('heading',{name:'Select Date & Time'}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`docs/evidence/ui/date-selection-${viewport.width}.png`,fullPage:true});checks.push({name:'Date and time step opens and inputs usable',passed:true});await page.getByRole('button',{name:'Continue'}).click();await page.getByRole('heading',{name:'Booking Summary'}).waitFor();await page.getByRole('checkbox').check();const submit=page.getByRole('button',{name:'Submit Request'});checks.push({name:'Summary enables submission after explicit rules acceptance',passed:await submit.isEnabled()});await page.screenshot({path:`docs/evidence/ui/booking-summary-${viewport.width}.png`,fullPage:true});await submit.click();await page.getByRole('alert').waitFor();checks.push({name:'Server action error shown inside booking screen',passed:await page.getByText('UI test action — no live booking is created.').isVisible()});
await page.goto('http://127.0.0.1:4178/?screen=booking&role=Student');await page.getByRole('button',{name:'Cancel booking',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();const box=await dialog.boundingBox();checks.push({name:'Cancellation confirmation fits viewport',passed:!!box&&box.x>=0&&box.y>=0&&box.x+box.width<=viewport.width+1&&box.y+box.height<=viewport.height+1});await page.keyboard.press('Escape');checks.push({name:'Escape closes accessible cancellation dialog',passed:await dialog.count()===0});
if(viewport.width<768){await page.goto('http://127.0.0.1:4178/?screen=dashboard&role=Lab%20Staff');await page.getByRole('button',{name:'Open staff navigation'}).click();checks.push({name:'Mobile staff menu exposes operational navigation',passed:await page.getByRole('navigation',{name:'Staff navigation'}).getByText('Request Approvals').isVisible()});}
await page.goto('http://127.0.0.1:4178/?screen=approvals&role=Student');checks.push({name:'Student denied approval workspace',passed:await page.getByRole('heading',{name:'Permission required'}).isVisible()});
}catch(error){checks.push({name:'Interaction exception',passed:false,error:error.message});}results.push({viewport,checks});await page.close();}
await fs.writeFile('docs/evidence/ui/interactions.json',JSON.stringify({scope:'Isolated UI fixtures and mock actions. Database mutation and live authentication are not exercised.',results},null,2));console.log(JSON.stringify(results,null,2));await browser.close();if(results.some(r=>r.checks.some(c=>!c.passed)))process.exitCode=1;

