import React from 'react';
import { createRoot } from 'react-dom/client';
import {AppShell} from '../../components/app-shell';
import {Dashboard,Browse,ResourceDetail,Book,Bookings,BookingDetail,Calendar,Notifications,Profile} from '../../components/screens/student';
import {Approvals,IssueReturn,Blocks,Rules,Admin} from '../../components/screens/operations';
import Reports from '../../components/screens/reports';
import {fixture} from './fixture';
import '../../app/globals.css';
const query=new URLSearchParams(window.location.search);const screen=query.get('screen')||'dashboard';const data=fixture(query.get('role')||'Student');
if(query.get('empty')==='true'){data.bookings=[];data.booking_items=[];data.availability=[];data.issue_returns=[];data.notifications=[];data.resource_blocks=[];}
if(query.get('noslots')==='true'){data.labs[0].status='Maintenance';}
const screens:Record<string,React.ReactNode>={dashboard:<Dashboard data={data}/>,browse:<Browse data={data} workspace/>,labs:<Browse data={data}/>,equipment:<Browse data={data} equipment/>,equipmentdetails:<ResourceDetail data={data} equipment id="equipment-0"/>,details:<ResourceDetail data={data} id="lab-a"/>,book:<Book data={data} query={{lab:'lab-a'}}/>,bookings:<Bookings data={data}/>,past:<Bookings data={data} tab="past"/>,cancelled:<Bookings data={data} tab="cancelled"/>,booking:<BookingDetail data={data} id="booking-1"/>,calendar:<Calendar data={data}/>,notifications:<Notifications data={data}/>,profile:<Profile data={data}/>,approvals:<Approvals data={data}/>,review:<Approvals data={data} id="booking-0"/>,issue:<IssueReturn data={data}/>,return:<IssueReturn data={data} tab="return"/>,blocks:<Blocks data={data}/>,rules:<Rules data={data}/>,users:<Admin data={data} section="users"/>,departments:<Admin data={data} section="departments"/>,categories:<Admin data={data} section="categories"/>,audit:<Admin data={data} section="audit"/>,adminlabs:<Admin data={data} section="labs"/>,adminequipment:<Admin data={data} section="equipment"/>,reports:<Reports analytics={{windowDays:60,total:60,approved:42,pending:6,cancelled:5,issued:112,overdue:5,damaged:2,monthly:[{name:'Aug',bookings:20},{name:'Sep',bookings:34},{name:'Oct',bookings:6}],departments:[{name:'Computer Science',bookings:28},{name:'Electrical Engineering',bookings:20},{name:'Applied Sciences',bookings:12}],peakHours:[{name:'09:00',bookings:10},{name:'11:00',bookings:22},{name:'13:00',bookings:17},{name:'15:00',bookings:11}],labUsage:data.labs.map((l,i)=>({name:l.name,bookings:18-i*3})),equipmentUsage:data.equipment.map((e,i)=>({name:e.name,quantity:25-i*3})),utilization:data.labs.map((l,i)=>({name:l.name,availableHours:540,bookedHours:45-i*5,utilization:8-i,bookings:18-i})),underusedLabs:data.labs.map((l,i)=>({name:l.name,availableHours:540,utilization:8-i})),rejectionReasons:[{name:'Resource unavailable',bookings:3},{name:'Outside approved session requirements',bookings:1}],utilizationDefinition:'UI test fixture values only; not measured database data.'}}/>};
createRoot(document.getElementById('root')!).render(<AppShell profile={data.profile as any}>{screens[screen]||screens.dashboard}</AppShell>);
