import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true,channel:'chrome'});
await fs.mkdir('docs/evidence/ui',{recursive:true});
const widths=[{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}];
const scenes=[['dashboard','Student'],['dashboard','Faculty'],['browse','Student'],['labs','Student'],['equipment','Student'],['equipmentdetails','Student'],['details','Student'],['book','Student'],['bookings','Student'],['past','Student'],['cancelled','Student'],['booking','Student'],['calendar','Student'],['notifications','Student'],['profile','Student'],['approvals','Lab Staff'],['review','Coordinator'],['issue','Lab Staff'],['return','Lab Staff'],['blocks','Lab Staff'],['rules','Coordinator'],['users','Admin'],['departments','Admin'],['categories','Admin'],['audit','Admin'],['adminlabs','Admin'],['adminequipment','Admin'],['reports','Admin'],['bookings','Student','empty=true'],['notifications','Student','empty=true'],['calendar','Student','empty=true'],['approvals','Lab Staff','empty=true'],['dashboard','Student','empty=true']];
const results=[];
for(const viewport of widths){const page=await browser.newPage({viewport});for(const [screen,role,extra=''] of scenes){const errors=[];const listener=e=>errors.push(e.message);page.on('pageerror',listener);await page.goto(`http://127.0.0.1:4178/?screen=${screen}&role=${encodeURIComponent(role)}&${extra}`);await page.waitForSelector('main');await page.waitForTimeout(150);const overflow=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,body:document.body.scrollWidth,elements:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,class:e.className,right:Math.round(e.getBoundingClientRect().right)})).slice(0,8)}));results.push({screen,role,extra,viewport,overflow:overflow.document>viewport.width+1,details:overflow,errors});if(['dashboard','browse','book','calendar','users','reports'].includes(screen))await page.screenshot({path:`docs/evidence/ui/${screen}${extra?'-empty':''}-${viewport.width}.png`,fullPage:true});page.off('pageerror',listener);}await page.close();}
await fs.writeFile('docs/evidence/ui/results.json',JSON.stringify({scope:'Isolated UI fixtures. This does not verify live authentication or database behavior.',checked:new Date().toISOString(),results},null,2));
const failures=results.filter(r=>r.overflow||r.errors.length);console.log(JSON.stringify({cases:results.length,failures},null,2));await browser.close();if(failures.length)process.exitCode=1;


