import {chromium,expect} from '@playwright/test';
import {createClient} from '@supabase/supabase-js';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.VERIFY_URL||'http://localhost:3000';
const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SECRET_KEY,{auth:{persistSession:false}});
const browser=await chromium.launch({headless:true,channel:'chrome'});const errors=[];const checks=[];await mkdir('docs/evidence/live',{recursive:true});
async function role(name,width=390,height=844){const context=await browser.newContext({viewport:{width,height}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/login`);await page.getByRole('button',{name,exact:false}).click();await page.waitForURL('**/dashboard',{timeout:60000});await page.waitForFunction(()=>document.documentElement.dataset.unilabReady==='true');return page;}
const purpose=`Browser verification ${Date.now()}`;const student=await role('Student');const start=new Date(Date.now()+12*60000);start.setSeconds(0,0);const end=new Date(+start+3600000);const local=d=>d.toLocaleString('sv-SE',{timeZone:'Asia/Karachi'}).replace(' ','T');
try{
await student.goto(`${base}/book?lab=10000000-0000-4000-8000-000000000100`);await student.waitForFunction(()=>document.documentElement.dataset.unilabReady==='true');await student.getByLabel('Purpose of booking',{exact:true}).fill(purpose);await student.getByLabel('Arduino Uno Kit quantity',{exact:true}).fill('1');await student.getByRole('button',{name:'Continue',exact:false}).click();await student.getByLabel('Date',{exact:true}).fill(local(start).slice(0,10));await student.getByLabel('Start time',{exact:true}).fill(local(start).slice(11,16));await student.getByLabel('End time',{exact:true}).fill(local(end).slice(11,16));await student.getByRole('heading',{name:'Select Date & Time'}).click();await student.getByRole('button',{name:'Continue',exact:false}).click();await student.getByRole('checkbox').check();await student.getByRole('button',{name:'Submit Request'}).click();await student.getByRole('heading',{name:'Request submitted!'}).waitFor({timeout:60000});await student.screenshot({path:'docs/evidence/live/request-submitted-390.png',fullPage:true});
let result=await db.from('bookings').select('*').eq('purpose',purpose).single();if(result.error)throw result.error;const id=result.data.id;checks.push({name:'Student submitted real lab+equipment request',passed:result.data.booking_status==='Pending Approval',bookingId:id});
// A second genuine request exercises conflict detection and database-validated alternatives.
await student.goto(`${base}/book?lab=10000000-0000-4000-8000-000000000100`);await student.waitForFunction(()=>document.documentElement.dataset.unilabReady==='true');await student.getByLabel('Purpose of booking',{exact:true}).fill(purpose+' conflict');await student.getByLabel('Arduino Uno Kit quantity',{exact:true}).fill('1');await student.getByRole('button',{name:'Continue'}).click();await student.getByLabel('Date',{exact:true}).fill(local(start).slice(0,10));await student.getByLabel('Start time',{exact:true}).fill(local(start).slice(11,16));await student.getByLabel('End time',{exact:true}).fill(local(end).slice(11,16));await student.getByRole('heading',{name:'Select Date & Time'}).click();await student.getByRole('button',{name:'Continue'}).click();await student.getByRole('checkbox').check();await student.getByRole('button',{name:'Submit Request'}).click();await student.getByRole('heading',{name:/alternative/i}).waitFor({timeout:60000});await student.screenshot({path:'docs/evidence/live/conflict-alternatives-390.png',fullPage:true});checks.push({name:'Conflicting request presents verified scored alternatives',passed:await student.locator('.alternative-card').count()>0});
const staff=await role('Lab Staff',1440,900);await staff.goto(`${base}/approvals/${id}`);await staff.getByRole('button',{name:'Approve & reserve'}).click();await expect.poll(async()=>{const r=await db.from('bookings').select('booking_status').eq('id',id).single();return r.data?.booking_status},{timeout:30000}).toBe('Reserved');result=await db.from('bookings').select('*').eq('id',id).single();checks.push({name:'Authorized staff approves reservation',passed:result.data?.booking_status==='Reserved'});await staff.screenshot({path:'docs/evidence/live/approved-1440.png',fullPage:true});
await staff.goto(`${base}/issue-return`);const card=staff.locator('.operation-card').filter({hasText:purpose});await card.getByRole('button',{name:'Confirm Equipment Issue'}).click();await staff.getByRole('dialog').getByRole('button',{name:'Confirm Equipment Issue',exact:true}).click();await expect.poll(async()=>{const r=await db.from('bookings').select('booking_status').eq('id',id).single();return r.data?.booking_status},{timeout:30000}).toBe('In Use');result=await db.from('bookings').select('*').eq('id',id).single();checks.push({name:'Actual equipment issue records custody',passed:result.data?.booking_status==='In Use'});
await staff.goto(`${base}/issue-return?tab=return`);const returning=staff.locator('.operation-card').filter({hasText:purpose});await returning.getByRole('button',{name:'Confirm Equipment Return'}).click();await staff.getByRole('dialog').getByRole('button',{name:'Confirm Equipment Return',exact:true}).click();await expect.poll(async()=>{const r=await db.from('bookings').select('booking_status').eq('id',id).single();return r.data?.booking_status},{timeout:30000}).toBe('Completed');result=await db.from('bookings').select('*').eq('id',id).single();const issued=await db.from('issue_returns').select('*').eq('booking_id',id);checks.push({name:'Actual equipment return closes booking',passed:result.data?.booking_status==='Completed'&&issued.data?.every(i=>i.returned_at&&i.returned_quantity===i.quantity)});
await student.goto(`${base}/bookings/${id}`);await student.getByText('Completed',{exact:true}).first().waitFor();await student.screenshot({path:'docs/evidence/live/completed-booking-390.png',fullPage:true});const notifications=await db.from('notifications').select('id,message').eq('booking_id',id);checks.push({name:'Lifecycle notifications persisted for requester',passed:(notifications.data?.length||0)>=3});const audit=await db.from('audit_log').select('action').eq('entity_id',id);checks.push({name:'Lifecycle audit trail recorded',passed:['booking.created','booking.approved','equipment.issued','equipment.returned'].every(action=>audit.data?.some(a=>a.action===action))});console.log(JSON.stringify({checks,pageErrors:errors},null,2));await writeFile('docs/evidence/live/core-flow.json',JSON.stringify({verified:new Date().toISOString(),scope:`Real ${base} UI, hosted Supabase Auth + database, persisted demonstration test booking`,checks,pageErrors:errors},null,2));if(checks.some(c=>!c.passed)||errors.length)process.exitCode=1;
}catch(e){await student.screenshot({path:'docs/evidence/live/flow-failure.png',fullPage:true});console.error('Live browser verification failed:',e.message);await writeFile('docs/evidence/live/core-flow-failure.json',JSON.stringify({checks,error:e.message,pageErrors:errors},null,2));process.exitCode=1;}finally{await browser.close()}



